---
baseurl: "/extend-the-docs"
description: The Just the Docs Jekyll theme extended
permalink: pretty
repository: Potherca/extend-the-docs
remote_theme: pmarsceill/just-the-docs
title: Extend the docs Jekyll theme
url: "https://pother.ca"

plugins:
  - github-pages

# Extend the Docs (Fork) settings
nav:
  exclude:
    - "/"
  recurse: true
  cross_repository:
    show_homepage: false # use the homepage (from the repository settings) instead of https://site.url/repository-name
    show_archived: false  # Whether to include repositories that have been archived (true) or not (false)

# Just the Docs (Source) settings
aux_links:
  "Potherca on GitHub":
    - "https://github.com/Potherca"
gh_edit_repository: https://github.com/Potherca/extend-the-docs
search_enabled: false
